# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Embedded_Systems_Sobel_Filter_HLS/IP_2.2/2.2_removing_conditionals/impl/verilog/sobel.xdc

# IP: ip/sobel_ap_dsqrt_29_no_dsp_64/sobel_ap_dsqrt_29_no_dsp_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sobel_ap_dsqrt_29_no_dsp_64 || ORIG_REF_NAME==sobel_ap_dsqrt_29_no_dsp_64}]

# IP: ip/sobel_ap_uitodp_4_no_dsp_32/sobel_ap_uitodp_4_no_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sobel_ap_uitodp_4_no_dsp_32 || ORIG_REF_NAME==sobel_ap_uitodp_4_no_dsp_32}]
